In [1]:
import numpy as np
import pandas as pd

In [2]:
def col_interval_generator(start_position, field_length, has_binary = False):
    column_intervals = []
    for i in range(len(start_position)):
        if (not has_binary):
            column_interval = (start_position[i] - 1, start_position[i] - 1 + field_length[i])
            column_intervals.append(column_interval)
        else:
            if (i != (len(start_position) - 1)):
                column_interval = (start_position[i] - 1, start_position[i] - 1 + field_length[i])
            else:
                column_interval = (start_position[i] - 1, start_position[i] - 1 + field_length[i] * 2)
            column_intervals.append(column_interval)
    return column_intervals

In [23]:
def read_data(filePath, fileType,firstLineHeader_T2, columnNames_T2, startPosition_T2, 
              fieldLength_T2, fieldConv_T2):
    if fileType == 2:
        column_intervals = col_interval_generator(start_position=startPosition_T2, field_length=fieldLength_T2, has_binary=False)
        if firstLineHeader_T2 == 1:
            df6 = pd.read_fwf(filePath, colspecs=column_intervals, header=0, converters=fieldConv_T2)
        else:
            df6 = pd.read_fwf(filePath, colspecs=column_intervals, header=None, names=columnNames_T2, converters=fieldConv_T2)
    return df6

In [24]:
#filePath = 'file1'
#filePath = 'file2'
#filePath = 'file3'
#filePath = 'file4'
#filePath = 'file5'
filePath = 'file6'


fileType = 2 #######################################################################
firstLineHeader_T2 = 0 # 1: the first line of the data file is header/ 0: not

# if firstLineHeader_T2 = 0, then specify column names at below (columnNames_T2)
columnNames_T2 = ["Unique_ID", "PIN"]
#"ACCOM_ADDR_TYPE_CD", "HOMEOWNER_IN"]
#columnNames_T2 = varname_list

# Provide start position of fields that you want to read in
startPosition_T2 = [307, 357] 
#startPosition_T2 = start_list

# Provide length of fields that you want to read in
fieldLength_T2 = [10, 19]
#fieldLength_T2 = len_list

# Provide format of each field that you want to read in as 'field name': format (str, int, etc.)
fieldConv_T2 = {"DataPrep_ID": str, "HASH_PIN": int}
#                 
#fieldConv_T2 = varformat_dict

In [25]:
df6 = read_data(filePath, fileType, firstLineHeader_T2, columnNames_T2, startPosition_T2, 
              fieldLength_T2, fieldConv_T2)

In [6]:
print(df1.head())

  DataPrep_ID     HASH_PIN
0  0000000001  16892328230
1  0000000002  43477726594
2  0000000003  34572250989
3  0000000004  43478657725
4  0000000005  18731057061

In [12]:
print(df2.head())

  DataPrep_ID     HASH_PIN
0  0000000001  16892328230
1  0000000002  43477726594
2  0000000003  34572250989
3  0000000004  43478657725
4  0000000005  18731057061

In [16]:
print(df3.head())

  DataPrep_ID     HASH_PIN
0  0000000001  16892328230
1  0000000002  43477726594
2  0000000003  34572250989
3  0000000004  43478657725
4  0000000005  18731057061

In [26]:
print(df4.head())

  DataPrep_ID     HASH_PIN
0  0000000001  16892328230
1  0000000002  43477726594
2  0000000003  34572250989
3  0000000004  43478657725
4  0000000005  18731057061

In [27]:
print(df5.head())

  DataPrep_ID     HASH_PIN
0  0000000001  16892328230
1  0000000002  43477726594
2  0000000003  34572250989
3  0000000004  43478657725
4  0000000005  18731057061

In [28]:
print(df6.head())

  DataPrep_ID     HASH_PIN
0  0000000001  16892328230
1  0000000002  43477726594
2  0000000003  34572250989
3  0000000004  43478657725
4  0000000005  18731057061

In [29]:
df1=df1.assign(date='2017-03-29')

In [30]:
print(df1)
df1.dtypes

      DataPrep_ID     HASH_PIN archive_date
0      0000000001  16892328230   2017-03-29
1      0000000002  43477726594   2017-03-29
2      0000000003  34572250989   2017-03-29
3      0000000004  43478657725   2017-03-29
4      0000000005  18731057061   2017-03-29
5      0000000006  38256475792   2017-03-29
6      0000000007  10680422643   2017-03-29
7      0000000008  53671470686   2017-03-29
8      0000000009  21764959211   2017-03-29
9      0000000010   8128296830   2017-03-29
10     0000000011  21401028594   2017-03-29
11     0000000012  43387566323   2017-03-29
12     0000000013  35517366390   2017-03-29
13     0000000014  26573016929   2017-03-29
14     0000000015  50601878527   2017-03-29
15     0000000016  37230743578   2017-03-29
16     0000000017  10799863316   2017-03-29
17     0000000018   3658009560   2017-03-29
18     0000000019  46062594741   2017-03-29
19     0000000020  42543246692   2017-03-29
20     0000000021  45318009999   2017-03-29
21     0000000022  45835892128   2017-03-29
22     0000000023  34777353447   2017-03-29
23     0000000024  51334431546   2017-03-29
24     0000000025  11369036715   2017-03-29
25     0000000026  21425618503   2017-03-29
26     0000000027   2846405451   2017-03-29
27     0000000028  51034381716   2017-03-29
28     0000000029  27075709474   2017-03-29
29     0000000030  30227893121   2017-03-29
...           ...          ...          ...
37172  0000039096  50658657325   2017-03-29
37173  0000039097  35335681250   2017-03-29
37174  0000039098  29287633023   2017-03-29
37175  0000039099  27628169598   2017-03-29
37176  0000039101  39999721525   2017-03-29
37177  0000039102  10801375580   2017-03-29
37178  0000039103  50936976398   2017-03-29
37179  0000039104  13335154600   2017-03-29
37180  0000039105  47781094653   2017-03-29
37181  0000039106  45374007901   2017-03-29
37182  0000039107  11653135414   2017-03-29
37183  0000039108  21438698898   2017-03-29
37184  0000039109  39840463631   2017-03-29
37185  0000039110   3698646106   2017-03-29
37186  0000039111   8687451241   2017-03-29
37187  0000039113  27551715447   2017-03-29
37188  0000039114  13807952723   2017-03-29
37189  0000039115  13807952723   2017-03-29
37190  0000039116   5384560908   2017-03-29
37191  0000039117  37570912353   2017-03-29
37192  0000039118  27412194569   2017-03-29
37193  0000039120  29445991827   2017-03-29
37194  0000039121  43051040064   2017-03-29
37195  0000039122  39905320530   2017-03-29
37196  0000039123  53355678747   2017-03-29
37197  0000039124  27276352664   2017-03-29
37198  0000039125  10706529812   2017-03-29
37199  0000039126   8129918380   2017-03-29
37200  0000039127   3643448322   2017-03-29
37201  0000039128   8062257537   2017-03-29

[37202 rows x 3 columns]

DataPrep_ID     object
HASH_PIN         int64
archive_date    object
dtype: object

In [31]:
df2=df2.assign(date='2017-07-29')
df3=df3.assign(date='2017-11-29')
df4=df4.assign(date='2018-03-31')
df5=df5.assign(date='2018-07-28')
df6=df6.assign(date='2018-11-28')

In [32]:
#df1.dtypes
#df2.dtypes
#df3.dtypes
#df4.dtypes
#df5.dtypes
#df6.dtypes

In [33]:
filePath = 'data.sas7bdat' 
fileType = 3

def read_data(filePath, fileType):
    if fileType == 3:
        Input_File = pd.read_sas(filePath, encoding = "ISO-8859-1")
        return Input_File

In [34]:
Input_File = read_data(filePath, fileType)

In [35]:
Input_File.head()

,Unique_Record_ID,Portfolio_Type,Product_Name,Interest_Rat_ Offered,Last_Name,First_Name,Middle_Initial,Generation_Code,House_Number,Stree_Direction,...,AAText5,AAText6,AAText7,AAText8,AAText9,AAText10,AAText11,AAText12,AAText13,Unique_Id
0,119817,Personal Loans,Personal Loan,11.00,Drayton,Tomas,A,NaN,NaN,NaN,...,Length of time revolving accounts have been es...,Proportion of loan balances to loan amounts is...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000000001
1,119819,Personal Loans,Debt Consolidation Loan,9.25,Bearam,Zoe,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000000002
2,119824,Auto,Auto Used,2.74,Madden,Robin,M,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000000003
3,119830,Auto,Auto Used,3.99,Brunard,Jean,S,NaN,NaN,NaN,...,Ratio of balance to limit on bank revolving or...,Too many inquiries last 12 months,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000000004
4,119838,Auto,Auto Used,2.99,Voitel,Nichole,C,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0000000005

In [36]:
Input_File.shape

(39129, 54)

In [37]:
print(Input_File.iloc[0])

Unique_Record_ID                                                          119817
Portfolio_Type                                                    Personal Loans
Product_Name                                                       Personal Loan
Interest_Rat_ Offered                                                      11.00
Last_Name                                                                Drayton
First_Name                                                                 Tomas
Middle_Initial                                                                 A
Generation_Code                                                              NaN
House_Number                                                                 NaN
Stree_Direction                                                              NaN
Street_Name                                                         4 Dennett Rd
Apt_ Number                                                                  NaN
City                                                                    Somerset
State                                                                         NJ
Zip                                                                        08873
Social_Security_Number                                                 141885349
Credit_Score_1                                                               714
Credit_Score_2                                                               NaN
Application_Date                                             2017-03-01 00:00:00
Client_Decision                                                           Denied
Worst_Performanc_Everrrr                                                       7
Manual_o_Automatic_Approval                                                  NaN
Final_Application_Status                                                  Denied
Referral_Reason                                                              NaN
Bookin_Date                                                                  NaN
Override_Reason_1                                                            NaN
Overrid_ Reaso_2                                                             NaN
Loan_Officer_Branch_ID                                                     10022
Application_Time                                                             NaN
Loan_Amount                                                                 1500
Loan_Term                                                                    NaN
Final_Interest                                                               NaN
ApplicationID                                                             122246
Note_Balance                                                                 NaN
Applicant_Status                                                         Primary
Debt_to_Income_Ratio                                                      1.0414
Total_Debt                                                                624.86
Total_Income                                                                 600
Product_Purpose                                                            Other
LoanNumber                                                                   NaN
AAText1                                                 Excessive unsecured debt
AAText2                        Lack of recent bank/national revolving informa...
AAText3                             Lack of recent revolving account information
AAText4                                                     Length of employment
AAText5                        Length of time revolving accounts have been es...
AAText6                        Proportion of loan balances to loan amounts is...
AAText7                                                                      NaN
AAText8                                                                      NaN
AAText9                                                                      NaN
AAText10                                                                     NaN
AAText11                                                                     NaN
AAText12                                                                     NaN
AAText13                                                                     NaN
Unique_Id                                                             0000000001
Name: 0, dtype: object

In [38]:
#Input_File['Application_Date'] = Input_File['Application_Date'].astype(int)

In [39]:
Input_File.dtypes

Unique_Record_ID                       object
Portfolio_Type                         object
Product_Name                           object
Interest_Rat_ Offered                  object
Last_Name                              object
First_Name                             object
Middle_Initial                         object
Generation_Code                        object
House_Number                           object
Stree_Direction                        object
Street_Name                            object
Apt_ Number                            object
City                                   object
State                                  object
Zip                                    object
Social_Security_Number                 object
Credit_Score_1                        float64
Credit_Score_2                         object
Application_Date               datetime64[ns]
Client_Decision                        object
Worst_Performanc_Everrrr               object
Manual_o_Automatic_Approval            object
Final_Application_Status               object
Referral_Reason                        object
Bookin_Date                            object
Override_Reason_1                      object
Overrid_ Reaso_2                       object
Loan_Officer_Branch_ID                 object
Application_Time                       object
Loan_Amount                           float64
Loan_Term                             float64
Final_Interest                         object
ApplicationID                         float64
Note_Balance                          float64
Applicant_Status                       object
Debt_to_Income_Ratio                  float64
Total_Debt                            float64
Total_Income                          float64
Product_Purpose                        object
LoanNumber                            float64
AAText1                                object
AAText2                                object
AAText3                                object
AAText4                                object
AAText5                                object
AAText6                                object
AAText7                                object
AAText8                                object
AAText9                                object
AAText10                               object
AAText11                               object
AAText12                               object
AAText13                               object
Unique_Id                              object
dtype: object

In [40]:
#app_date=list(Input_File['Application_Date'].unique())

In [41]:
print(Input_File['Application_Date'].unique())

['2017-03-01T00:00:00.000000000' '2017-03-02T00:00:00.000000000'
 '2017-03-03T00:00:00.000000000' '2017-03-04T00:00:00.000000000'
 '2017-03-05T00:00:00.000000000' '2017-03-06T00:00:00.000000000'
 '2017-03-07T00:00:00.000000000' '2017-03-08T00:00:00.000000000'
 '2017-03-09T00:00:00.000000000' '2017-03-10T00:00:00.000000000'
 '2017-03-11T00:00:00.000000000' '2017-03-12T00:00:00.000000000'
 '2017-03-13T00:00:00.000000000' '2017-03-14T00:00:00.000000000'
 '2017-03-15T00:00:00.000000000' '2017-03-16T00:00:00.000000000'
 '2017-03-17T00:00:00.000000000' '2017-03-18T00:00:00.000000000'
 '2017-03-19T00:00:00.000000000' '2017-03-20T00:00:00.000000000'
 '2017-03-21T00:00:00.000000000' '2017-03-22T00:00:00.000000000'
 '2017-03-23T00:00:00.000000000' '2017-03-24T00:00:00.000000000'
 '2017-03-25T00:00:00.000000000' '2017-03-26T00:00:00.000000000'
 '2017-03-27T00:00:00.000000000' '2017-03-28T00:00:00.000000000'
 '2017-03-29T00:00:00.000000000' '2017-03-30T00:00:00.000000000'
 '2017-03-31T00:00:00.000000000' '2017-04-01T00:00:00.000000000'
 '2017-04-02T00:00:00.000000000' '2017-04-03T00:00:00.000000000'
 '2017-04-04T00:00:00.000000000' '2017-04-05T00:00:00.000000000'
 '2017-04-06T00:00:00.000000000' '2017-04-07T00:00:00.000000000'
 '2017-04-08T00:00:00.000000000' '2017-04-09T00:00:00.000000000'
 '2017-04-10T00:00:00.000000000' '2017-04-11T00:00:00.000000000'
 '2017-04-12T00:00:00.000000000' '2017-04-13T00:00:00.000000000'
 '2017-04-14T00:00:00.000000000' '2017-04-15T00:00:00.000000000'
 '2017-04-16T00:00:00.000000000' '2017-04-17T00:00:00.000000000'
 '2017-04-18T00:00:00.000000000' '2017-04-19T00:00:00.000000000'
 '2017-04-20T00:00:00.000000000' '2017-04-21T00:00:00.000000000'
 '2017-04-22T00:00:00.000000000' '2017-04-23T00:00:00.000000000'
 '2017-04-24T00:00:00.000000000' '2017-04-25T00:00:00.000000000'
 '2017-04-26T00:00:00.000000000' '2017-04-27T00:00:00.000000000'
 '2017-04-28T00:00:00.000000000' '2017-04-29T00:00:00.000000000'
 '2017-04-30T00:00:00.000000000' '2017-05-01T00:00:00.000000000'
 '2017-05-02T00:00:00.000000000' '2017-05-03T00:00:00.000000000'
 '2017-05-04T00:00:00.000000000' '2017-05-05T00:00:00.000000000'
 '2017-05-06T00:00:00.000000000' '2017-05-07T00:00:00.000000000'
 '2017-05-08T00:00:00.000000000' '2017-05-09T00:00:00.000000000'
 '2017-05-10T00:00:00.000000000' '2017-05-11T00:00:00.000000000'
 '2017-05-12T00:00:00.000000000' '2017-05-13T00:00:00.000000000'
 '2017-05-14T00:00:00.000000000' '2017-05-15T00:00:00.000000000'
 '2017-05-16T00:00:00.000000000' '2017-05-17T00:00:00.000000000'
 '2017-05-18T00:00:00.000000000' '2017-05-19T00:00:00.000000000'
 '2017-05-20T00:00:00.000000000' '2017-05-21T00:00:00.000000000'
 '2017-05-22T00:00:00.000000000' '2017-05-23T00:00:00.000000000'
 '2017-05-24T00:00:00.000000000' '2017-05-25T00:00:00.000000000'
 '2017-05-26T00:00:00.000000000' '2017-05-27T00:00:00.000000000'
 '2017-05-28T00:00:00.000000000' '2017-05-29T00:00:00.000000000'
 '2017-05-30T00:00:00.000000000' '2017-05-31T00:00:00.000000000'
 '2017-06-01T00:00:00.000000000' '2017-06-02T00:00:00.000000000'
 '2017-06-03T00:00:00.000000000' '2017-06-04T00:00:00.000000000'
 '2017-06-05T00:00:00.000000000' '2017-06-06T00:00:00.000000000'
 '2017-06-07T00:00:00.000000000' '2017-06-08T00:00:00.000000000'
 '2017-06-09T00:00:00.000000000' '2017-06-10T00:00:00.000000000'
 '2017-06-11T00:00:00.000000000' '2017-06-12T00:00:00.000000000'
 '2017-06-13T00:00:00.000000000' '2017-06-14T00:00:00.000000000'
 '2017-06-15T00:00:00.000000000' '2017-06-16T00:00:00.000000000'
 '2017-06-17T00:00:00.000000000' '2017-06-19T00:00:00.000000000'
 '2017-06-20T00:00:00.000000000' '2017-06-21T00:00:00.000000000'
 '2017-06-22T00:00:00.000000000' '2017-06-23T00:00:00.000000000'
 '2017-06-24T00:00:00.000000000' '2017-06-25T00:00:00.000000000'
 '2017-06-26T00:00:00.000000000' '2017-06-27T00:00:00.000000000'
 '2017-06-28T00:00:00.000000000' '2017-06-29T00:00:00.000000000'
 '2017-06-30T00:00:00.000000000' '2017-07-01T00:00:00.000000000'
 '2017-07-02T00:00:00.000000000' '2017-07-03T00:00:00.000000000'
 '2017-07-04T00:00:00.000000000' '2017-07-05T00:00:00.000000000'
 '2017-07-06T00:00:00.000000000' '2017-07-07T00:00:00.000000000'
 '2017-07-08T00:00:00.000000000' '2017-07-09T00:00:00.000000000'
 '2017-07-10T00:00:00.000000000' '2017-07-11T00:00:00.000000000'
 '2017-07-12T00:00:00.000000000' '2017-07-13T00:00:00.000000000'
 '2017-07-14T00:00:00.000000000' '2017-07-15T00:00:00.000000000'
 '2017-07-16T00:00:00.000000000' '2017-07-17T00:00:00.000000000'
 '2017-07-18T00:00:00.000000000' '2017-07-19T00:00:00.000000000'
 '2017-07-20T00:00:00.000000000' '2017-07-21T00:00:00.000000000'
 '2017-07-22T00:00:00.000000000' '2017-07-23T00:00:00.000000000'
 '2017-07-24T00:00:00.000000000' '2017-07-25T00:00:00.000000000'
 '2017-07-26T00:00:00.000000000' '2017-07-27T00:00:00.000000000'
 '2017-07-28T00:00:00.000000000' '2017-07-29T00:00:00.000000000'
 '2017-07-30T00:00:00.000000000' '2017-07-31T00:00:00.000000000'
 '2017-08-01T00:00:00.000000000' '2017-08-02T00:00:00.000000000'
 '2017-08-03T00:00:00.000000000' '2017-08-04T00:00:00.000000000'
 '2017-08-05T00:00:00.000000000' '2017-08-06T00:00:00.000000000'
 '2017-08-07T00:00:00.000000000' '2017-08-08T00:00:00.000000000'
 '2017-08-09T00:00:00.000000000' '2017-08-10T00:00:00.000000000'
 '2017-08-11T00:00:00.000000000' '2017-08-12T00:00:00.000000000'
 '2017-08-13T00:00:00.000000000' '2017-08-14T00:00:00.000000000'
 '2017-08-15T00:00:00.000000000' '2017-08-16T00:00:00.000000000'
 '2017-08-17T00:00:00.000000000' '2017-08-18T00:00:00.000000000'
 '2017-08-19T00:00:00.000000000' '2017-08-20T00:00:00.000000000'
 '2017-08-21T00:00:00.000000000' '2017-08-22T00:00:00.000000000'
 '2017-08-23T00:00:00.000000000' '2017-08-24T00:00:00.000000000'
 '2017-08-25T00:00:00.000000000' '2017-08-26T00:00:00.000000000'
 '2017-08-27T00:00:00.000000000' '2017-08-28T00:00:00.000000000'
 '2017-08-29T00:00:00.000000000' '2017-08-30T00:00:00.000000000'
 '2017-08-31T00:00:00.000000000' '2017-09-01T00:00:00.000000000'
 '2017-09-02T00:00:00.000000000' '2017-09-03T00:00:00.000000000'
 '2017-09-04T00:00:00.000000000' '2017-09-05T00:00:00.000000000'
 '2017-09-06T00:00:00.000000000' '2017-09-07T00:00:00.000000000'
 '2017-09-08T00:00:00.000000000' '2017-09-09T00:00:00.000000000'
 '2017-09-10T00:00:00.000000000' '2017-09-11T00:00:00.000000000'
 '2017-09-12T00:00:00.000000000' '2017-09-13T00:00:00.000000000'
 '2017-09-14T00:00:00.000000000' '2017-09-15T00:00:00.000000000'
 '2017-09-16T00:00:00.000000000' '2017-09-17T00:00:00.000000000'
 '2017-09-18T00:00:00.000000000' '2017-09-19T00:00:00.000000000'
 '2017-09-20T00:00:00.000000000' '2017-09-21T00:00:00.000000000'
 '2017-09-22T00:00:00.000000000' '2017-09-23T00:00:00.000000000'
 '2017-09-24T00:00:00.000000000' '2017-09-25T00:00:00.000000000'
 '2017-09-26T00:00:00.000000000' '2017-09-27T00:00:00.000000000'
 '2017-09-28T00:00:00.000000000' '2017-09-29T00:00:00.000000000'
 '2017-09-30T00:00:00.000000000' '2017-10-01T00:00:00.000000000'
 '2017-10-02T00:00:00.000000000' '2017-10-03T00:00:00.000000000'
 '2017-10-04T00:00:00.000000000' '2017-10-05T00:00:00.000000000'
 '2017-10-06T00:00:00.000000000' '2017-10-07T00:00:00.000000000'
 '2017-10-08T00:00:00.000000000' '2017-10-09T00:00:00.000000000'
 '2017-10-10T00:00:00.000000000' '2017-10-11T00:00:00.000000000'
 '2017-10-12T00:00:00.000000000' '2017-10-13T00:00:00.000000000'
 '2017-10-14T00:00:00.000000000' '2017-10-15T00:00:00.000000000'
 '2017-10-16T00:00:00.000000000' '2017-10-17T00:00:00.000000000'
 '2017-10-18T00:00:00.000000000' '2017-10-19T00:00:00.000000000'
 '2017-10-20T00:00:00.000000000' '2017-10-21T00:00:00.000000000'
 '2017-10-22T00:00:00.000000000' '2017-10-23T00:00:00.000000000'
 '2017-10-24T00:00:00.000000000' '2017-10-25T00:00:00.000000000'
 '2017-10-26T00:00:00.000000000' '2017-10-27T00:00:00.000000000'
 '2017-10-28T00:00:00.000000000' '2017-10-29T00:00:00.000000000'
 '2017-10-30T00:00:00.000000000' '2017-10-31T00:00:00.000000000'
 '2017-11-01T00:00:00.000000000' '2017-11-02T00:00:00.000000000'
 '2017-11-03T00:00:00.000000000' '2017-11-04T00:00:00.000000000'
 '2017-11-05T00:00:00.000000000' '2017-11-06T00:00:00.000000000'
 '2017-11-07T00:00:00.000000000' '2017-11-08T00:00:00.000000000'
 '2017-11-09T00:00:00.000000000' '2017-11-10T00:00:00.000000000'
 '2017-11-11T00:00:00.000000000' '2017-11-12T00:00:00.000000000'
 '2017-11-13T00:00:00.000000000' '2017-11-14T00:00:00.000000000'
 '2017-11-15T00:00:00.000000000' '2017-11-16T00:00:00.000000000'
 '2017-11-17T00:00:00.000000000' '2017-11-18T00:00:00.000000000'
 '2017-11-19T00:00:00.000000000' '2017-11-20T00:00:00.000000000'
 '2017-11-21T00:00:00.000000000' '2017-11-22T00:00:00.000000000'
 '2017-11-23T00:00:00.000000000' '2017-11-24T00:00:00.000000000'
 '2017-11-25T00:00:00.000000000' '2017-11-26T00:00:00.000000000'
 '2017-11-27T00:00:00.000000000' '2017-11-28T00:00:00.000000000'
 '2017-11-29T00:00:00.000000000' '2017-11-30T00:00:00.000000000'
 '2017-12-01T00:00:00.000000000' '2017-12-02T00:00:00.000000000'
 '2017-12-03T00:00:00.000000000' '2017-12-04T00:00:00.000000000'
 '2017-12-05T00:00:00.000000000' '2017-12-06T00:00:00.000000000'
 '2017-12-07T00:00:00.000000000' '2017-12-08T00:00:00.000000000'
 '2017-12-09T00:00:00.000000000' '2017-12-11T00:00:00.000000000'
 '2017-12-12T00:00:00.000000000' '2017-12-13T00:00:00.000000000'
 '2017-12-14T00:00:00.000000000' '2017-12-15T00:00:00.000000000'
 '2017-12-16T00:00:00.000000000' '2017-12-17T00:00:00.000000000'
 '2017-12-18T00:00:00.000000000' '2017-12-19T00:00:00.000000000'
 '2017-12-20T00:00:00.000000000' '2017-12-21T00:00:00.000000000'
 '2017-12-22T00:00:00.000000000' '2017-12-23T00:00:00.000000000'
 '2017-12-24T00:00:00.000000000' '2017-12-25T00:00:00.000000000'
 '2017-12-26T00:00:00.000000000' '2017-12-27T00:00:00.000000000'
 '2017-12-28T00:00:00.000000000' '2017-12-29T00:00:00.000000000'
 '2017-12-30T00:00:00.000000000' '2017-12-31T00:00:00.000000000'
 '2018-01-01T00:00:00.000000000' '2018-01-02T00:00:00.000000000'
 '2018-01-03T00:00:00.000000000' '2018-01-04T00:00:00.000000000'
 '2018-01-05T00:00:00.000000000' '2018-01-06T00:00:00.000000000'
 '2018-01-07T00:00:00.000000000' '2018-01-08T00:00:00.000000000'
 '2018-01-09T00:00:00.000000000' '2018-01-10T00:00:00.000000000'
 '2018-01-11T00:00:00.000000000' '2018-01-12T00:00:00.000000000'
 '2018-01-13T00:00:00.000000000' '2018-01-14T00:00:00.000000000'
 '2018-01-15T00:00:00.000000000' '2018-01-16T00:00:00.000000000'
 '2018-01-17T00:00:00.000000000' '2018-01-18T00:00:00.000000000'
 '2018-01-19T00:00:00.000000000' '2018-01-20T00:00:00.000000000'
 '2018-01-21T00:00:00.000000000' '2018-01-22T00:00:00.000000000'
 '2018-01-23T00:00:00.000000000' '2018-01-24T00:00:00.000000000'
 '2018-01-25T00:00:00.000000000' '2018-01-26T00:00:00.000000000'
 '2018-01-27T00:00:00.000000000' '2018-01-28T00:00:00.000000000'
 '2018-01-29T00:00:00.000000000' '2018-01-30T00:00:00.000000000'
 '2018-01-31T00:00:00.000000000' '2018-02-01T00:00:00.000000000'
 '2018-02-02T00:00:00.000000000' '2018-02-03T00:00:00.000000000'
 '2018-02-04T00:00:00.000000000' '2018-02-05T00:00:00.000000000'
 '2018-02-06T00:00:00.000000000' '2018-02-07T00:00:00.000000000'
 '2018-02-08T00:00:00.000000000' '2018-02-09T00:00:00.000000000'
 '2018-02-10T00:00:00.000000000' '2018-02-11T00:00:00.000000000'
 '2018-02-12T00:00:00.000000000' '2018-02-13T00:00:00.000000000'
 '2018-02-14T00:00:00.000000000' '2018-02-15T00:00:00.000000000'
 '2018-02-16T00:00:00.000000000' '2018-02-17T00:00:00.000000000'
 '2018-02-18T00:00:00.000000000' '2018-02-19T00:00:00.000000000'
 '2018-02-20T00:00:00.000000000' '2018-02-21T00:00:00.000000000'
 '2018-02-22T00:00:00.000000000' '2018-02-23T00:00:00.000000000'
 '2018-02-24T00:00:00.000000000' '2018-02-25T00:00:00.000000000'
 '2018-02-26T00:00:00.000000000' '2018-02-27T00:00:00.000000000'
 '2018-02-28T00:00:00.000000000' '2018-03-01T00:00:00.000000000'
 '2018-03-02T00:00:00.000000000' '2018-03-03T00:00:00.000000000'
 '2018-03-04T00:00:00.000000000' '2018-03-05T00:00:00.000000000'
 '2018-03-06T00:00:00.000000000' '2018-03-07T00:00:00.000000000'
 '2018-03-08T00:00:00.000000000' '2018-03-09T00:00:00.000000000'
 '2018-03-10T00:00:00.000000000' '2018-03-11T00:00:00.000000000'
 '2018-03-12T00:00:00.000000000' '2018-03-13T00:00:00.000000000'
 '2018-03-14T00:00:00.000000000' '2018-03-15T00:00:00.000000000'
 '2018-03-16T00:00:00.000000000' '2018-03-17T00:00:00.000000000'
 '2018-03-18T00:00:00.000000000' '2018-03-19T00:00:00.000000000'
 '2018-03-20T00:00:00.000000000' '2018-03-21T00:00:00.000000000'
 '2018-03-22T00:00:00.000000000' '2018-03-23T00:00:00.000000000'
 '2018-03-24T00:00:00.000000000' '2018-03-25T00:00:00.000000000'
 '2018-03-26T00:00:00.000000000' '2018-03-27T00:00:00.000000000'
 '2018-03-28T00:00:00.000000000' '2018-03-29T00:00:00.000000000'
 '2018-03-30T00:00:00.000000000' '2018-03-31T00:00:00.000000000'
 '2018-04-01T00:00:00.000000000' '2018-04-02T00:00:00.000000000'
 '2018-04-03T00:00:00.000000000' '2018-04-04T00:00:00.000000000'
 '2018-04-05T00:00:00.000000000' '2018-04-06T00:00:00.000000000'
 '2018-04-07T00:00:00.000000000' '2018-04-08T00:00:00.000000000'
 '2018-04-09T00:00:00.000000000' '2018-04-10T00:00:00.000000000'
 '2018-04-11T00:00:00.000000000' '2018-04-12T00:00:00.000000000'
 '2018-04-13T00:00:00.000000000' '2018-04-14T00:00:00.000000000'
 '2018-04-15T00:00:00.000000000' '2018-04-16T00:00:00.000000000'
 '2018-04-17T00:00:00.000000000' '2018-04-18T00:00:00.000000000'
 '2018-04-19T00:00:00.000000000' '2018-04-20T00:00:00.000000000'
 '2018-04-21T00:00:00.000000000' '2018-04-22T00:00:00.000000000'
 '2018-04-23T00:00:00.000000000' '2018-04-24T00:00:00.000000000'
 '2018-04-25T00:00:00.000000000' '2018-04-26T00:00:00.000000000'
 '2018-04-27T00:00:00.000000000' '2018-04-28T00:00:00.000000000'
 '2018-04-29T00:00:00.000000000' '2018-04-30T00:00:00.000000000'
 '2018-05-01T00:00:00.000000000' '2018-05-02T00:00:00.000000000'
 '2018-05-03T00:00:00.000000000' '2018-05-04T00:00:00.000000000'
 '2018-05-05T00:00:00.000000000' '2018-05-06T00:00:00.000000000'
 '2018-05-07T00:00:00.000000000' '2018-05-08T00:00:00.000000000'
 '2018-05-09T00:00:00.000000000' '2018-05-10T00:00:00.000000000'
 '2018-05-11T00:00:00.000000000' '2018-05-12T00:00:00.000000000'
 '2018-05-13T00:00:00.000000000' '2018-05-14T00:00:00.000000000'
 '2018-05-15T00:00:00.000000000' '2018-05-16T00:00:00.000000000'
 '2018-05-17T00:00:00.000000000' '2018-05-18T00:00:00.000000000'
 '2018-05-19T00:00:00.000000000' '2018-05-20T00:00:00.000000000'
 '2018-05-21T00:00:00.000000000' '2018-05-22T00:00:00.000000000'
 '2018-05-23T00:00:00.000000000' '2018-05-24T00:00:00.000000000'
 '2018-05-25T00:00:00.000000000' '2018-05-26T00:00:00.000000000'
 '2018-05-27T00:00:00.000000000' '2018-05-28T00:00:00.000000000'
 '2018-05-29T00:00:00.000000000' '2018-05-30T00:00:00.000000000'
 '2018-05-31T00:00:00.000000000' '2018-06-01T00:00:00.000000000'
 '2018-06-02T00:00:00.000000000' '2018-06-03T00:00:00.000000000'
 '2018-06-04T00:00:00.000000000' '2018-06-05T00:00:00.000000000'
 '2018-06-06T00:00:00.000000000' '2018-06-07T00:00:00.000000000'
 '2018-06-08T00:00:00.000000000' '2018-06-09T00:00:00.000000000'
 '2018-06-10T00:00:00.000000000' '2018-06-11T00:00:00.000000000'
 '2018-06-12T00:00:00.000000000' '2018-06-13T00:00:00.000000000'
 '2018-06-14T00:00:00.000000000' '2018-06-15T00:00:00.000000000'
 '2018-06-16T00:00:00.000000000' '2018-06-17T00:00:00.000000000'
 '2018-06-18T00:00:00.000000000' '2018-06-19T00:00:00.000000000'
 '2018-06-20T00:00:00.000000000' '2018-06-21T00:00:00.000000000'
 '2018-06-22T00:00:00.000000000' '2018-06-23T00:00:00.000000000'
 '2018-06-24T00:00:00.000000000' '2018-06-25T00:00:00.000000000'
 '2018-06-26T00:00:00.000000000' '2018-06-27T00:00:00.000000000'
 '2018-06-28T00:00:00.000000000' '2018-06-29T00:00:00.000000000'
 '2018-06-30T00:00:00.000000000' '2018-07-01T00:00:00.000000000'
 '2018-07-02T00:00:00.000000000' '2018-07-03T00:00:00.000000000'
 '2018-07-04T00:00:00.000000000' '2018-07-05T00:00:00.000000000'
 '2018-07-06T00:00:00.000000000' '2018-07-07T00:00:00.000000000'
 '2018-07-08T00:00:00.000000000' '2018-07-09T00:00:00.000000000'
 '2018-07-10T00:00:00.000000000' '2018-07-11T00:00:00.000000000'
 '2018-07-12T00:00:00.000000000' '2018-07-13T00:00:00.000000000'
 '2018-07-14T00:00:00.000000000' '2018-07-15T00:00:00.000000000'
 '2018-07-16T00:00:00.000000000' '2018-07-17T00:00:00.000000000'
 '2018-07-18T00:00:00.000000000' '2018-07-19T00:00:00.000000000'
 '2018-07-20T00:00:00.000000000' '2018-07-21T00:00:00.000000000'
 '2018-07-22T00:00:00.000000000' '2018-07-23T00:00:00.000000000'
 '2018-07-24T00:00:00.000000000' '2018-07-25T00:00:00.000000000'
 '2018-07-26T00:00:00.000000000' '2018-07-27T00:00:00.000000000'
 '2018-07-28T00:00:00.000000000' '2018-07-29T00:00:00.000000000'
 '2018-07-30T00:00:00.000000000' '2018-07-31T00:00:00.000000000'
 '2018-08-01T00:00:00.000000000' '2018-08-02T00:00:00.000000000'
 '2018-08-03T00:00:00.000000000' '2018-08-04T00:00:00.000000000'
 '2018-08-05T00:00:00.000000000' '2018-08-06T00:00:00.000000000'
 '2018-08-07T00:00:00.000000000' '2018-08-08T00:00:00.000000000'
 '2018-08-09T00:00:00.000000000' '2018-08-10T00:00:00.000000000'
 '2018-08-11T00:00:00.000000000' '2018-08-12T00:00:00.000000000'
 '2018-08-13T00:00:00.000000000' '2018-08-14T00:00:00.000000000'
 '2018-08-15T00:00:00.000000000' '2018-08-16T00:00:00.000000000'
 '2018-08-17T00:00:00.000000000' '2018-08-18T00:00:00.000000000'
 '2018-08-19T00:00:00.000000000' '2018-08-20T00:00:00.000000000'
 '2018-08-21T00:00:00.000000000' '2018-08-22T00:00:00.000000000'
 '2018-08-23T00:00:00.000000000' '2018-08-24T00:00:00.000000000'
 '2018-08-25T00:00:00.000000000' '2018-08-26T00:00:00.000000000'
 '2018-08-27T00:00:00.000000000' '2018-08-28T00:00:00.000000000'
 '2018-08-29T00:00:00.000000000' '2018-08-30T00:00:00.000000000'
 '2018-08-31T00:00:00.000000000' '2018-09-01T00:00:00.000000000'
 '2018-09-02T00:00:00.000000000' '2018-09-03T00:00:00.000000000'
 '2018-09-04T00:00:00.000000000' '2018-09-05T00:00:00.000000000'
 '2018-09-06T00:00:00.000000000' '2018-09-07T00:00:00.000000000'
 '2018-09-08T00:00:00.000000000' '2018-09-09T00:00:00.000000000'
 '2018-09-10T00:00:00.000000000' '2018-09-11T00:00:00.000000000'
 '2018-09-12T00:00:00.000000000' '2018-09-13T00:00:00.000000000'
 '2018-09-14T00:00:00.000000000' '2018-09-15T00:00:00.000000000'
 '2018-09-16T00:00:00.000000000' '2018-09-17T00:00:00.000000000'
 '2018-09-18T00:00:00.000000000' '2018-09-19T00:00:00.000000000'
 '2018-09-20T00:00:00.000000000' '2018-09-21T00:00:00.000000000'
 '2018-09-22T00:00:00.000000000' '2018-09-23T00:00:00.000000000'
 '2018-09-24T00:00:00.000000000' '2018-09-25T00:00:00.000000000'
 '2018-09-26T00:00:00.000000000' '2018-09-27T00:00:00.000000000'
 '2018-09-28T00:00:00.000000000' '2018-09-29T00:00:00.000000000'
 '2018-09-30T00:00:00.000000000' '2018-10-01T00:00:00.000000000'
 '2018-10-02T00:00:00.000000000' '2018-10-03T00:00:00.000000000'
 '2018-10-04T00:00:00.000000000' '2018-10-05T00:00:00.000000000'
 '2018-10-06T00:00:00.000000000' '2018-10-07T00:00:00.000000000'
 '2018-10-08T00:00:00.000000000' '2018-10-09T00:00:00.000000000'
 '2018-10-10T00:00:00.000000000' '2018-10-11T00:00:00.000000000'
 '2018-10-12T00:00:00.000000000' '2018-10-13T00:00:00.000000000'
 '2018-10-14T00:00:00.000000000' '2018-10-15T00:00:00.000000000'
 '2018-10-16T00:00:00.000000000' '2018-10-17T00:00:00.000000000'
 '2018-10-18T00:00:00.000000000' '2018-10-19T00:00:00.000000000'
 '2018-10-20T00:00:00.000000000' '2018-10-21T00:00:00.000000000'
 '2018-10-22T00:00:00.000000000' '2018-10-23T00:00:00.000000000'
 '2018-10-24T00:00:00.000000000' '2018-10-25T00:00:00.000000000'
 '2018-10-26T00:00:00.000000000' '2018-10-27T00:00:00.000000000'
 '2018-10-28T00:00:00.000000000' '2018-10-29T00:00:00.000000000'
 '2018-10-30T00:00:00.000000000' '2018-10-31T00:00:00.000000000'
 '2018-11-01T00:00:00.000000000' '2018-11-02T00:00:00.000000000'
 '2018-11-03T00:00:00.000000000' '2018-11-04T00:00:00.000000000'
 '2018-11-05T00:00:00.000000000' '2018-11-06T00:00:00.000000000'

In [47]:
import datetime
dates = pd.to_datetime(pd.Series(Input_File['Application_Date']), format = '%Y%m%d')
#dates = dates.apply(lambda x: x.strftime('%Y-%m-%d'))
#Input_File['App_dates'] = datetime.date(Input_File['Application_Date'], format = '%Y%m%d')
#Input_File['App_dates'].apply(lambda x: x.strftime('%Y-%m-%d'))

In [48]:
dates.unique()

array(['2017-03-01T00:00:00.000000000', '2017-03-02T00:00:00.000000000',
       '2017-03-03T00:00:00.000000000', '2017-03-04T00:00:00.000000000',
       '2017-03-05T00:00:00.000000000', '2017-03-06T00:00:00.000000000',
       '2017-03-07T00:00:00.000000000', '2017-03-08T00:00:00.000000000',
       '2017-03-09T00:00:00.000000000', '2017-03-10T00:00:00.000000000',
       '2017-03-11T00:00:00.000000000', '2017-03-12T00:00:00.000000000',
       '2017-03-13T00:00:00.000000000', '2017-03-14T00:00:00.000000000',
       '2017-03-15T00:00:00.000000000', '2017-03-16T00:00:00.000000000',
       '2017-03-17T00:00:00.000000000', '2017-03-18T00:00:00.000000000',
       '2017-03-19T00:00:00.000000000', '2017-03-20T00:00:00.000000000',
       '2017-03-21T00:00:00.000000000', '2017-03-22T00:00:00.000000000',
       '2017-03-23T00:00:00.000000000', '2017-03-24T00:00:00.000000000',
       '2017-03-25T00:00:00.000000000', '2017-03-26T00:00:00.000000000',
       '2017-03-27T00:00:00.000000000', '2017-03-28T00:00:00.000000000',
       '2017-03-29T00:00:00.000000000', '2017-03-30T00:00:00.000000000',
       '2017-03-31T00:00:00.000000000', '2017-04-01T00:00:00.000000000',
       '2017-04-02T00:00:00.000000000', '2017-04-03T00:00:00.000000000',
       '2017-04-04T00:00:00.000000000', '2017-04-05T00:00:00.000000000',
       '2017-04-06T00:00:00.000000000', '2017-04-07T00:00:00.000000000',
       '2017-04-08T00:00:00.000000000', '2017-04-09T00:00:00.000000000',
       '2017-04-10T00:00:00.000000000', '2017-04-11T00:00:00.000000000',
       '2017-04-12T00:00:00.000000000', '2017-04-13T00:00:00.000000000',
       '2017-04-14T00:00:00.000000000', '2017-04-15T00:00:00.000000000',
       '2017-04-16T00:00:00.000000000', '2017-04-17T00:00:00.000000000',
       '2017-04-18T00:00:00.000000000', '2017-04-19T00:00:00.000000000',
       '2017-04-20T00:00:00.000000000', '2017-04-21T00:00:00.000000000',
       '2017-04-22T00:00:00.000000000', '2017-04-23T00:00:00.000000000',
       '2017-04-24T00:00:00.000000000', '2017-04-25T00:00:00.000000000',
       '2017-04-26T00:00:00.000000000', '2017-04-27T00:00:00.000000000',
       '2017-04-28T00:00:00.000000000', '2017-04-29T00:00:00.000000000',
       '2017-04-30T00:00:00.000000000', '2017-05-01T00:00:00.000000000',
       '2017-05-02T00:00:00.000000000', '2017-05-03T00:00:00.000000000',
       '2017-05-04T00:00:00.000000000', '2017-05-05T00:00:00.000000000',
       '2017-05-06T00:00:00.000000000', '2017-05-07T00:00:00.000000000',
       '2017-05-08T00:00:00.000000000', '2017-05-09T00:00:00.000000000',
       '2017-05-10T00:00:00.000000000', '2017-05-11T00:00:00.000000000',
       '2017-05-12T00:00:00.000000000', '2017-05-13T00:00:00.000000000',
       '2017-05-14T00:00:00.000000000', '2017-05-15T00:00:00.000000000',
       '2017-05-16T00:00:00.000000000', '2017-05-17T00:00:00.000000000',
       '2017-05-18T00:00:00.000000000', '2017-05-19T00:00:00.000000000',
       '2017-05-20T00:00:00.000000000', '2017-05-21T00:00:00.000000000',
       '2017-05-22T00:00:00.000000000', '2017-05-23T00:00:00.000000000',
       '2017-05-24T00:00:00.000000000', '2017-05-25T00:00:00.000000000',
       '2017-05-26T00:00:00.000000000', '2017-05-27T00:00:00.000000000',
       '2017-05-28T00:00:00.000000000', '2017-05-29T00:00:00.000000000',
       '2017-05-30T00:00:00.000000000', '2017-05-31T00:00:00.000000000',
       '2017-06-01T00:00:00.000000000', '2017-06-02T00:00:00.000000000',
       '2017-06-03T00:00:00.000000000', '2017-06-04T00:00:00.000000000',
       '2017-06-05T00:00:00.000000000', '2017-06-06T00:00:00.000000000',
       '2017-06-07T00:00:00.000000000', '2017-06-08T00:00:00.000000000',
       '2017-06-09T00:00:00.000000000', '2017-06-10T00:00:00.000000000',
       '2017-06-11T00:00:00.000000000', '2017-06-12T00:00:00.000000000',
       '2017-06-13T00:00:00.000000000', '2017-06-14T00:00:00.000000000',
       '2017-06-15T00:00:00.000000000', '2017-06-16T00:00:00.000000000',
       '2017-06-17T00:00:00.000000000', '2017-06-19T00:00:00.000000000',
       '2017-06-20T00:00:00.000000000', '2017-06-21T00:00:00.000000000',
       '2017-06-22T00:00:00.000000000', '2017-06-23T00:00:00.000000000',
       '2017-06-24T00:00:00.000000000', '2017-06-25T00:00:00.000000000',
       '2017-06-26T00:00:00.000000000', '2017-06-27T00:00:00.000000000',
       '2017-06-28T00:00:00.000000000', '2017-06-29T00:00:00.000000000',
       '2017-06-30T00:00:00.000000000', '2017-07-01T00:00:00.000000000',
       '2017-07-02T00:00:00.000000000', '2017-07-03T00:00:00.000000000',
       '2017-07-04T00:00:00.000000000', '2017-07-05T00:00:00.000000000',
       '2017-07-06T00:00:00.000000000', '2017-07-07T00:00:00.000000000',
       '2017-07-08T00:00:00.000000000', '2017-07-09T00:00:00.000000000',
       '2017-07-10T00:00:00.000000000', '2017-07-11T00:00:00.000000000',
       '2017-07-12T00:00:00.000000000', '2017-07-13T00:00:00.000000000',
       '2017-07-14T00:00:00.000000000', '2017-07-15T00:00:00.000000000',
       '2017-07-16T00:00:00.000000000', '2017-07-17T00:00:00.000000000',
       '2017-07-18T00:00:00.000000000', '2017-07-19T00:00:00.000000000',
       '2017-07-20T00:00:00.000000000', '2017-07-21T00:00:00.000000000',
       '2017-07-22T00:00:00.000000000', '2017-07-23T00:00:00.000000000',
       '2017-07-24T00:00:00.000000000', '2017-07-25T00:00:00.000000000',
       '2017-07-26T00:00:00.000000000', '2017-07-27T00:00:00.000000000',
       '2017-07-28T00:00:00.000000000', '2017-07-29T00:00:00.000000000',
       '2017-07-30T00:00:00.000000000', '2017-07-31T00:00:00.000000000',
       '2017-08-01T00:00:00.000000000', '2017-08-02T00:00:00.000000000',
       '2017-08-03T00:00:00.000000000', '2017-08-04T00:00:00.000000000',
       '2017-08-05T00:00:00.000000000', '2017-08-06T00:00:00.000000000',
       '2017-08-07T00:00:00.000000000', '2017-08-08T00:00:00.000000000',
       '2017-08-09T00:00:00.000000000', '2017-08-10T00:00:00.000000000',
       '2017-08-11T00:00:00.000000000', '2017-08-12T00:00:00.000000000',
       '2017-08-13T00:00:00.000000000', '2017-08-14T00:00:00.000000000',
       '2017-08-15T00:00:00.000000000', '2017-08-16T00:00:00.000000000',
       '2017-08-17T00:00:00.000000000', '2017-08-18T00:00:00.000000000',
       '2017-08-19T00:00:00.000000000', '2017-08-20T00:00:00.000000000',
       '2017-08-21T00:00:00.000000000', '2017-08-22T00:00:00.000000000',
       '2017-08-23T00:00:00.000000000', '2017-08-24T00:00:00.000000000',
       '2017-08-25T00:00:00.000000000', '2017-08-26T00:00:00.000000000',
       '2017-08-27T00:00:00.000000000', '2017-08-28T00:00:00.000000000',
       '2017-08-29T00:00:00.000000000', '2017-08-30T00:00:00.000000000',
       '2017-08-31T00:00:00.000000000', '2017-09-01T00:00:00.000000000',
       '2017-09-02T00:00:00.000000000', '2017-09-03T00:00:00.000000000',
       '2017-09-04T00:00:00.000000000', '2017-09-05T00:00:00.000000000',
       '2017-09-06T00:00:00.000000000', '2017-09-07T00:00:00.000000000',
       '2017-09-08T00:00:00.000000000', '2017-09-09T00:00:00.000000000',
       '2017-09-10T00:00:00.000000000', '2017-09-11T00:00:00.000000000',
       '2017-09-12T00:00:00.000000000', '2017-09-13T00:00:00.000000000',
       '2017-09-14T00:00:00.000000000', '2017-09-15T00:00:00.000000000',
       '2017-09-16T00:00:00.000000000', '2017-09-17T00:00:00.000000000',
       '2017-09-18T00:00:00.000000000', '2017-09-19T00:00:00.000000000',
       '2017-09-20T00:00:00.000000000', '2017-09-21T00:00:00.000000000',
       '2017-09-22T00:00:00.000000000', '2017-09-23T00:00:00.000000000',
       '2017-09-24T00:00:00.000000000', '2017-09-25T00:00:00.000000000',
       '2017-09-26T00:00:00.000000000', '2017-09-27T00:00:00.000000000',
       '2017-09-28T00:00:00.000000000', '2017-09-29T00:00:00.000000000',
       '2017-09-30T00:00:00.000000000', '2017-10-01T00:00:00.000000000',
       '2017-10-02T00:00:00.000000000', '2017-10-03T00:00:00.000000000',
       '2017-10-04T00:00:00.000000000', '2017-10-05T00:00:00.000000000',
       '2017-10-06T00:00:00.000000000', '2017-10-07T00:00:00.000000000',
       '2017-10-08T00:00:00.000000000', '2017-10-09T00:00:00.000000000',
       '2017-10-10T00:00:00.000000000', '2017-10-11T00:00:00.000000000',
       '2017-10-12T00:00:00.000000000', '2017-10-13T00:00:00.000000000',
       '2017-10-14T00:00:00.000000000', '2017-10-15T00:00:00.000000000',
       '2017-10-16T00:00:00.000000000', '2017-10-17T00:00:00.000000000',
       '2017-10-18T00:00:00.000000000', '2017-10-19T00:00:00.000000000',
       '2017-10-20T00:00:00.000000000', '2017-10-21T00:00:00.000000000',
       '2017-10-22T00:00:00.000000000', '2017-10-23T00:00:00.000000000',
       '2017-10-24T00:00:00.000000000', '2017-10-25T00:00:00.000000000',
       '2017-10-26T00:00:00.000000000', '2017-10-27T00:00:00.000000000',
       '2017-10-28T00:00:00.000000000', '2017-10-29T00:00:00.000000000',
       '2017-10-30T00:00:00.000000000', '2017-10-31T00:00:00.000000000',
       '2017-11-01T00:00:00.000000000', '2017-11-02T00:00:00.000000000',
       '2017-11-03T00:00:00.000000000', '2017-11-04T00:00:00.000000000',
       '2017-11-05T00:00:00.000000000', '2017-11-06T00:00:00.000000000',
       '2017-11-07T00:00:00.000000000', '2017-11-08T00:00:00.000000000',
       '2017-11-09T00:00:00.000000000', '2017-11-10T00:00:00.000000000',
       '2017-11-11T00:00:00.000000000', '2017-11-12T00:00:00.000000000',
       '2017-11-13T00:00:00.000000000', '2017-11-14T00:00:00.000000000',
       '2017-11-15T00:00:00.000000000', '2017-11-16T00:00:00.000000000',
       '2017-11-17T00:00:00.000000000', '2017-11-18T00:00:00.000000000',
       '2017-11-19T00:00:00.000000000', '2017-11-20T00:00:00.000000000',
       '2017-11-21T00:00:00.000000000', '2017-11-22T00:00:00.000000000',
       '2017-11-23T00:00:00.000000000', '2017-11-24T00:00:00.000000000',
       '2017-11-25T00:00:00.000000000', '2017-11-26T00:00:00.000000000',
       '2017-11-27T00:00:00.000000000', '2017-11-28T00:00:00.000000000',
       '2017-11-29T00:00:00.000000000', '2017-11-30T00:00:00.000000000',
       '2017-12-01T00:00:00.000000000', '2017-12-02T00:00:00.000000000',
       '2017-12-03T00:00:00.000000000', '2017-12-04T00:00:00.000000000',
       '2017-12-05T00:00:00.000000000', '2017-12-06T00:00:00.000000000',
       '2017-12-07T00:00:00.000000000', '2017-12-08T00:00:00.000000000',
       '2017-12-09T00:00:00.000000000', '2017-12-11T00:00:00.000000000',
       '2017-12-12T00:00:00.000000000', '2017-12-13T00:00:00.000000000',
       '2017-12-14T00:00:00.000000000', '2017-12-15T00:00:00.000000000',
       '2017-12-16T00:00:00.000000000', '2017-12-17T00:00:00.000000000',
       '2017-12-18T00:00:00.000000000', '2017-12-19T00:00:00.000000000',
       '2017-12-20T00:00:00.000000000', '2017-12-21T00:00:00.000000000',
       '2017-12-22T00:00:00.000000000', '2017-12-23T00:00:00.000000000',
       '2017-12-24T00:00:00.000000000', '2017-12-25T00:00:00.000000000',
       '2017-12-26T00:00:00.000000000', '2017-12-27T00:00:00.000000000',
       '2017-12-28T00:00:00.000000000', '2017-12-29T00:00:00.000000000',
       '2017-12-30T00:00:00.000000000', '2017-12-31T00:00:00.000000000',
       '2018-01-01T00:00:00.000000000', '2018-01-02T00:00:00.000000000',
       '2018-01-03T00:00:00.000000000', '2018-01-04T00:00:00.000000000',
       '2018-01-05T00:00:00.000000000', '2018-01-06T00:00:00.000000000',
       '2018-01-07T00:00:00.000000000', '2018-01-08T00:00:00.000000000',
       '2018-01-09T00:00:00.000000000', '2018-01-10T00:00:00.000000000',
       '2018-01-11T00:00:00.000000000', '2018-01-12T00:00:00.000000000',
       '2018-01-13T00:00:00.000000000', '2018-01-14T00:00:00.000000000',
       '2018-01-15T00:00:00.000000000', '2018-01-16T00:00:00.000000000',
       '2018-01-17T00:00:00.000000000', '2018-01-18T00:00:00.000000000',
       '2018-01-19T00:00:00.000000000', '2018-01-20T00:00:00.000000000',
       '2018-01-21T00:00:00.000000000', '2018-01-22T00:00:00.000000000',
       '2018-01-23T00:00:00.000000000', '2018-01-24T00:00:00.000000000',
       '2018-01-25T00:00:00.000000000', '2018-01-26T00:00:00.000000000',
       '2018-01-27T00:00:00.000000000', '2018-01-28T00:00:00.000000000',
       '2018-01-29T00:00:00.000000000', '2018-01-30T00:00:00.000000000',
       '2018-01-31T00:00:00.000000000', '2018-02-01T00:00:00.000000000',
       '2018-02-02T00:00:00.000000000', '2018-02-03T00:00:00.000000000',
       '2018-02-04T00:00:00.000000000', '2018-02-05T00:00:00.000000000',
       '2018-02-06T00:00:00.000000000', '2018-02-07T00:00:00.000000000',
       '2018-02-08T00:00:00.000000000', '2018-02-09T00:00:00.000000000',
       '2018-02-10T00:00:00.000000000', '2018-02-11T00:00:00.000000000',
       '2018-02-12T00:00:00.000000000', '2018-02-13T00:00:00.000000000',
       '2018-02-14T00:00:00.000000000', '2018-02-15T00:00:00.000000000',
       '2018-02-16T00:00:00.000000000', '2018-02-17T00:00:00.000000000',
       '2018-02-18T00:00:00.000000000', '2018-02-19T00:00:00.000000000',
       '2018-02-20T00:00:00.000000000', '2018-02-21T00:00:00.000000000',
       '2018-02-22T00:00:00.000000000', '2018-02-23T00:00:00.000000000',
       '2018-02-24T00:00:00.000000000', '2018-02-25T00:00:00.000000000',
       '2018-02-26T00:00:00.000000000', '2018-02-27T00:00:00.000000000',
       '2018-02-28T00:00:00.000000000', '2018-03-01T00:00:00.000000000',
       '2018-03-02T00:00:00.000000000', '2018-03-03T00:00:00.000000000',
       '2018-03-04T00:00:00.000000000', '2018-03-05T00:00:00.000000000',
       '2018-03-06T00:00:00.000000000', '2018-03-07T00:00:00.000000000',
       '2018-03-08T00:00:00.000000000', '2018-03-09T00:00:00.000000000',
       '2018-03-10T00:00:00.000000000', '2018-03-11T00:00:00.000000000',
       '2018-03-12T00:00:00.000000000', '2018-03-13T00:00:00.000000000',
       '2018-03-14T00:00:00.000000000', '2018-03-15T00:00:00.000000000',
       '2018-03-16T00:00:00.000000000', '2018-03-17T00:00:00.000000000',
       '2018-03-18T00:00:00.000000000', '2018-03-19T00:00:00.000000000',
       '2018-03-20T00:00:00.000000000', '2018-03-21T00:00:00.000000000',
       '2018-03-22T00:00:00.000000000', '2018-03-23T00:00:00.000000000',
       '2018-03-24T00:00:00.000000000', '2018-03-25T00:00:00.000000000',
       '2018-03-26T00:00:00.000000000', '2018-03-27T00:00:00.000000000',
       '2018-03-28T00:00:00.000000000', '2018-03-29T00:00:00.000000000',
       '2018-03-30T00:00:00.000000000', '2018-03-31T00:00:00.000000000',
       '2018-04-01T00:00:00.000000000', '2018-04-02T00:00:00.000000000',
       '2018-04-03T00:00:00.000000000', '2018-04-04T00:00:00.000000000',
       '2018-04-05T00:00:00.000000000', '2018-04-06T00:00:00.000000000',
       '2018-04-07T00:00:00.000000000', '2018-04-08T00:00:00.000000000',
       '2018-04-09T00:00:00.000000000', '2018-04-10T00:00:00.000000000',
       '2018-04-11T00:00:00.000000000', '2018-04-12T00:00:00.000000000',
       '2018-04-13T00:00:00.000000000', '2018-04-14T00:00:00.000000000',
       '2018-04-15T00:00:00.000000000', '2018-04-16T00:00:00.000000000',
       '2018-04-17T00:00:00.000000000', '2018-04-18T00:00:00.000000000',
       '2018-04-19T00:00:00.000000000', '2018-04-20T00:00:00.000000000',
       '2018-04-21T00:00:00.000000000', '2018-04-22T00:00:00.000000000',
       '2018-04-23T00:00:00.000000000', '2018-04-24T00:00:00.000000000',
       '2018-04-25T00:00:00.000000000', '2018-04-26T00:00:00.000000000',
       '2018-04-27T00:00:00.000000000', '2018-04-28T00:00:00.000000000',
       '2018-04-29T00:00:00.000000000', '2018-04-30T00:00:00.000000000',
       '2018-05-01T00:00:00.000000000', '2018-05-02T00:00:00.000000000',
       '2018-05-03T00:00:00.000000000', '2018-05-04T00:00:00.000000000',
       '2018-05-05T00:00:00.000000000', '2018-05-06T00:00:00.000000000',
       '2018-05-07T00:00:00.000000000', '2018-05-08T00:00:00.000000000',
       '2018-05-09T00:00:00.000000000', '2018-05-10T00:00:00.000000000',
       '2018-05-11T00:00:00.000000000', '2018-05-12T00:00:00.000000000',
       '2018-05-13T00:00:00.000000000', '2018-05-14T00:00:00.000000000',
       '2018-05-15T00:00:00.000000000', '2018-05-16T00:00:00.000000000',
       '2018-05-17T00:00:00.000000000', '2018-05-18T00:00:00.000000000',
       '2018-05-19T00:00:00.000000000', '2018-05-20T00:00:00.000000000',
       '2018-05-21T00:00:00.000000000', '2018-05-22T00:00:00.000000000',
       '2018-05-23T00:00:00.000000000', '2018-05-24T00:00:00.000000000',
       '2018-05-25T00:00:00.000000000', '2018-05-26T00:00:00.000000000',
       '2018-05-27T00:00:00.000000000', '2018-05-28T00:00:00.000000000',
       '2018-05-29T00:00:00.000000000', '2018-05-30T00:00:00.000000000',
       '2018-05-31T00:00:00.000000000', '2018-06-01T00:00:00.000000000',
       '2018-06-02T00:00:00.000000000', '2018-06-03T00:00:00.000000000',
       '2018-06-04T00:00:00.000000000', '2018-06-05T00:00:00.000000000',
       '2018-06-06T00:00:00.000000000', '2018-06-07T00:00:00.000000000',
       '2018-06-08T00:00:00.000000000', '2018-06-09T00:00:00.000000000',
       '2018-06-10T00:00:00.000000000', '2018-06-11T00:00:00.000000000',
       '2018-06-12T00:00:00.000000000', '2018-06-13T00:00:00.000000000',
       '2018-06-14T00:00:00.000000000', '2018-06-15T00:00:00.000000000',
       '2018-06-16T00:00:00.000000000', '2018-06-17T00:00:00.000000000',
       '2018-06-18T00:00:00.000000000', '2018-06-19T00:00:00.000000000',
       '2018-06-20T00:00:00.000000000', '2018-06-21T00:00:00.000000000',
       '2018-06-22T00:00:00.000000000', '2018-06-23T00:00:00.000000000',
       '2018-06-24T00:00:00.000000000', '2018-06-25T00:00:00.000000000',
       '2018-06-26T00:00:00.000000000', '2018-06-27T00:00:00.000000000',
       '2018-06-28T00:00:00.000000000', '2018-06-29T00:00:00.000000000',
       '2018-06-30T00:00:00.000000000', '2018-07-01T00:00:00.000000000',
       '2018-07-02T00:00:00.000000000', '2018-07-03T00:00:00.000000000',
       '2018-07-04T00:00:00.000000000', '2018-07-05T00:00:00.000000000',
       '2018-07-06T00:00:00.000000000', '2018-07-07T00:00:00.000000000',
       '2018-07-08T00:00:00.000000000', '2018-07-09T00:00:00.000000000',
       '2018-07-10T00:00:00.000000000', '2018-07-11T00:00:00.000000000',
       '2018-07-12T00:00:00.000000000', '2018-07-13T00:00:00.000000000',
       '2018-07-14T00:00:00.000000000', '2018-07-15T00:00:00.000000000',
       '2018-07-16T00:00:00.000000000', '2018-07-17T00:00:00.000000000',
       '2018-07-18T00:00:00.000000000', '2018-07-19T00:00:00.000000000',
       '2018-07-20T00:00:00.000000000', '2018-07-21T00:00:00.000000000',
       '2018-07-22T00:00:00.000000000', '2018-07-23T00:00:00.000000000',
       '2018-07-24T00:00:00.000000000', '2018-07-25T00:00:00.000000000',
       '2018-07-26T00:00:00.000000000', '2018-07-27T00:00:00.000000000',
       '2018-07-28T00:00:00.000000000', '2018-07-29T00:00:00.000000000',
       '2018-07-30T00:00:00.000000000', '2018-07-31T00:00:00.000000000',
       '2018-08-01T00:00:00.000000000', '2018-08-02T00:00:00.000000000',
       '2018-08-03T00:00:00.000000000', '2018-08-04T00:00:00.000000000',
       '2018-08-05T00:00:00.000000000', '2018-08-06T00:00:00.000000000',
       '2018-08-07T00:00:00.000000000', '2018-08-08T00:00:00.000000000',
       '2018-08-09T00:00:00.000000000', '2018-08-10T00:00:00.000000000',
       '2018-08-11T00:00:00.000000000', '2018-08-12T00:00:00.000000000',
       '2018-08-13T00:00:00.000000000', '2018-08-14T00:00:00.000000000',
       '2018-08-15T00:00:00.000000000', '2018-08-16T00:00:00.000000000',
       '2018-08-17T00:00:00.000000000', '2018-08-18T00:00:00.000000000',
       '2018-08-19T00:00:00.000000000', '2018-08-20T00:00:00.000000000',
       '2018-08-21T00:00:00.000000000', '2018-08-22T00:00:00.000000000',
       '2018-08-23T00:00:00.000000000', '2018-08-24T00:00:00.000000000',
       '2018-08-25T00:00:00.000000000', '2018-08-26T00:00:00.000000000',
       '2018-08-27T00:00:00.000000000', '2018-08-28T00:00:00.000000000',
       '2018-08-29T00:00:00.000000000', '2018-08-30T00:00:00.000000000',

In [ ]:
print(Input_File.iloc[0])

In [ ]:
merge_final1= pd.merge(Input_File, df1, on='Unique_ID', how='outer',indicator=True)

In [ ]:
#merge_final1 = pd.merge(left=Input_File, right=df1, how='left', left_on='Unique_Id', right_on='DataPrep_ID')

In [ ]:
merge_final1.head()
#final1['Application_Date'].head()

In [ ]:
merge_final2= pd.merge(Input_File, df2, on='Unique_ID', how='outer',indicator=True)
merge_final3= pd.merge(Input_File, df3, on='Unique_ID', how='outer',indicator=True)
merge_final4= pd.merge(Input_File, df4, on='Unique_ID', how='outer',indicator=True)
merge_final5= pd.merge(Input_File, df5, on='Unique_ID', how='outer',indicator=True)
merge_final6= pd.merge(Input_File, df6, on='Unique_ID', how='outer',indicator=True)

In [ ]:
final1= merge_final1[['Unique_ID', 'Application_Date', 'Portfolio_Type', 'Credit_Score_1', 'Worst_Performance', 'Client_Decision','date']].copy()

In [ ]:
final1.head()

In [ ]:
#check the count of input file and final1 file
final1.shape

In [ ]:
print(final1['date'].unique())

In [ ]:
final1 = final1[final1['date'] == '2017-03-29']

In [ ]:
#final1.shape
final1.head()
#final1['archive_date'].unique()

In [ ]:
final1.shape

In [ ]:
final1['date'].unique()

In [ ]:
final2= merge_final2[['Unique_ID', 'Application_Date', 'Portfolio_Type', 'Credit_Score_1', 'Worst_Performance', 'Client_Decision','date']].copy()
final3= merge_final3[['Unique_ID', 'Application_Date', 'Portfolio_Type', 'Credit_Score_1', 'Worst_Performance', 'Client_Decision','date']].copy()
final4= merge_final4[['Unique_ID', 'Application_Date', 'Portfolio_Type', 'Credit_Score_1', 'Worst_Performance', 'Client_Decision','date']].copy()
final5= merge_final5[['Unique_ID', 'Application_Date', 'Portfolio_Type', 'Credit_Score_1', 'Worst_Performance', 'Client_Decision','date']].copy()
final6= merge_final6[['Unique_ID', 'Application_Date', 'Portfolio_Type', 'Credit_Score_1', 'Worst_Performance', 'Client_Decision','date']].copy()

In [ ]:
final2 = final2[final2['date'] == '2017-07-29']
final3 = final3[final3['date'] == '2017-11-29']
final4 = final4[final4['date'] == '2018-03-31']
final5 = final5[final5['date'] == '2018-07-28']
final6 = final6[final6['date'] == '2018-11-28']

In [ ]:
final2.shape

In [ ]:
final3.shape

In [ ]:
final4.shape

In [ ]:
final5.shape

In [ ]:
final6.shape

In [ ]:
from functools import reduce

final_merge = reduce(lambda x,y: pd.merge(x,y, on='Unique_ID', how='outer'), [final1, final2, final3, final4, final5, final6])

In [ ]:
final_merge.head()
final_merge.shape